### ISSUE TITLE
See3CAM_CU51: "Trigger Mode Enabling Failed"

### ISSUE THREAD

**Issue by neherh** [econsysqtcam/qtcam#14]
I have used the See3CAM_CU51 camera and every time I attempt to go to click the  button 'Trigger Mode' in the 'Extension Settings' tab and I get a Failure error of, "Trigger Mode enabling failed". What is the issue? I tried with 2 cameras and I still get this error. 

Using the github qtcam I followed the instructions by compiling the code in the commandline:
- change common.h LAUNCHPAD to 0
- $ qmake
- $ make

![triggerfail](https://cloud.githubusercontent.com/assets/14037248/24266000/b9d4508e-0fdb-11e7-911f-2fa7ab453063.jpg)

**Comment by econsysqtcam** [comment]
Please make sure that you are launching the application using following command

**$ sudo ./Qtcam**

That is you need to launch application with sudo[root user permission].

**Comment by neherh** [comment]
I see. So I am assuming that the 'Trigger Mode' failed as a result of not having sudo permission. 

Thanks!!
