### ISSUE TITLE
Building on 16.10

### ISSUE THREAD

**Issue by justynb** [econsysqtcam/qtcam#16]
Makefile:773: warning: overriding recipe for target 'install_itemfolder_01'
Makefile:764: warning: ignoring old recipe for target 'install_itemfolder_01'
Makefile:777: warning: overriding recipe for target 'uninstall_itemfolder_01'
Makefile:768: warning: ignoring old recipe for target 'uninstall_itemfolder_01'
g++ -c -m64 -pipe -O2 -Wall -W -D__STDC_CONSTANT_MACROS -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iqtquick2applicationviewer -Iv4l2headers/include -isystem /usr/include -isystem /usr/include/libusb-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
In file included from /usr/include/c++/6/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6/algorithm:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:88,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
                 from main.cpp:21:
/usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
Makefile:582: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by econsysqtcam** [comment]
please use the following flag while running the qmake command.

$  /home/@user/Qt5.2.1/5.2.1/gcc_64/bin/qmake  **QMAKE_DEFAULT_INCDIRS=""**
