### ISSUE TITLE
qtcam bundles various libraries

### ISSUE THREAD

**Issue by Germano0** [econsysqtcam/qtcam#2]
Hi. I am interested in packaging qtcam for Fedora and push it into Fedora official repository. I would like to ask you one thing about your software: the reasons why qtcam bundles various libraries. All main Linux distributions guidelines avoid shipping bundled libraries that already are shipped inside distribution's repository. Basically, the prohibition on bundling is there for several reasons:
- security - we can fix the vulnerabilities in one place, the shared library, and every package depending on it is not vulnerable anymore;
- forking - if everyone is bundling their own fork, it gets harder to fix bugs, including security vulnerabilities and it creates more work for every maintainer involved as the forks diverge;
- general bug fixes and features - every package depending on a shared library gets the benefits of bugfixes and new features instantly (and we have the option to package a parallel-installable older version if a depending package can't be updated/fixed to work with the latest library version).

Concerning Fedora, the packaging guidelines are explained at https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

Best regards

**Comment by mahaecon** [comment]
Dear Germano, 
Thanks for your message and interest to push this into Fedora. We would be happy if you could do that. 
When we first started this application development, we were more focused on supporting our camera customers with a solid Linux application. Later we felt the need for it in open source and posted it in GitHub. We were offering this application packages to Linux Newbies as well and sometimes we faced issues that they could not install all dependencies properly or some dep installation failed. Thats the reason for the bundling. We understand that its not a good idea and we already have made a version with no bundling. We can update that for your Fedora push. Also can you please email us directly to qtcam@e-consystems.com with how you would expect the source code to be, to expedite the move into fedora and we can defintely help you with that. 

Warm Regards, 
Maharajan Veerabahu

**Comment by Germano0** [comment]
Hi Maharajan @mahaecon , thank you for your message. I am replying to you here (instead of replying to qtcam@e-consystems.com ) because there are many other Fedora developers interested in our conversation.

> We were offering this application packages to Linux Newbies as well and sometimes we faced issues that they could not install all dependencies properly or some dep installation failed.

To avoid these problems you could provide a note in install instructions with the list of dependencies that need to be installed

> Also can you please email us directly to qtcam@e-consystems.com with how you would expect the source code to be, to expedite the move into fedora and we can defintely help you with that. 

I have talked with some Fedora senior developers and they told me that any suggestion will be provided to you when the software will be under package review. So I think that the first your step is to provide a source code without bundled libraries.

Thank you and have a nice day

**Comment by mahaecon** [comment]
Dear Germano, 
Thanks for the detailed response. Yes, Lets continue our conversation in this thread, if that's of value to the others in the community. 
We are currently working on uploading the source code without the bundled libraries. 
Our team would update and comment on this same thread on what we do.

**Comment by mahaecon** [comment]
Dear Germano, 
The current source in the GItHub does not have any bundled libraries. Please use this source and let me know how we can help to move this into Fedora releases.

**Comment by Germano0** [comment]
Hi Maharajan, thank you very much, I am going to try the code immediately

**Comment by mahaecon** [comment]
Dear Germano, 
Hope you are able to compile and work with it ? Please let me know if you require any support from us

**Comment by Germano0** [comment]
Hi, I opened https://github.com/econsysqtcam/qtcam/issues/5

**Comment by mahaecon** [comment]
Oops !! Missed that. my bad. We would respond to you on that
