### ISSUE TITLE
'make install' installs into wrong qml directory

### ISSUE THREAD

**Issue by jsseng** [econsysqtcam/qtcam#24]
I compiled from source which proceeded fine, but when I ran 'make install' it does the following:

`cp -f -R /home/jseng/qtcam/src/qml/qtcam /usr//qml/`

It seems to not install into the /usr/share/qml directory.  When I try to start the program, I then get an error that it cannot find /usr/share/qml/qtcam/Views/qtcam.qml

When I fix the makefile manually, the install works.

**Comment by econsysqtcam** [comment]
We are maintaining the qml path based on installation of qtcam. 
1. Installation via ubuntu launchpad .Here qml path is "/usr/share/qml/qtcam"
2. Compiling source and launch application from current directory. Here qml path is "<current directory>/qml/qtcam/"
To maintain above , the flag LAUNCHPAD is used in file named "common.h". By default it is 1.
#if LAUNCHPAD
    viewer.setMainQmlFile(QStringLiteral("/usr/share/qml/qtcam/Views/qtcam.qml"));
#else
    viewer.setMainQmlFile(QStringLiteral("qml/qtcam/Views/qtcam.qml"));
#endif
So it will work out If you launch from current directory without doing make install.

If you do $make install, The qml file will be installed in /usr/ .  But source code refers the path "/usr/share/".  So It throws the error that it cannot find /usr/share/qml/qtcam/Views/qtcam.qml.

**Comment by jsseng** [comment]
Ok.
