### ISSUE TITLE
No extensions available for the selected camera

### ISSUE THREAD

**Issue by jsseng** [econsysqtcam/qtcam#25]
I have a See3Cam_CU20 (HDR).  I compiled from source and Qtcam runs, but when I select 'Extension Settings', I get the message 'No Extensions available for the selected camera.'

It is the 2nd camera in my device list.

I can change the standard camera settings fine (capture resolution, frame rate...).

**Comment by econsysqtcam** [comment]
Please make sure you followed the steps below to compile and launch the application. 
1.  cd src/
2.  Set LAUNCHPAD macro in common.h to 0. 
     **#define LAUNCHPAD 0**   [This is to take qml from current path]
3.  Run qmake
      **$ <Qt_installed path>/Qt5.2.1/5.2.1/gcc_64/bin/qmake**
4.  Run make
      **$ make**
5.  Execute the application.
     **$ sudo ./Qtcam**
