### ISSUE TITLE
How to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by truonggiang0710** [econsysqtcam/qtcam#39]

**Comment by jdehaan** [comment]
Remove /usr/include from INCLUDEPATH inside pro file and prepend AV_ to some constants appearing in errors on compilation. I could then compile and run the application under focal fossa.

**Comment by spiderkeys** [comment]
I was also able to get it building on 20.04 by doing the following:
  - In qtcam.pro, add "core" and "gui" to the "QT +=" line:
```
QT += core gui widgets concurrent multimedia
```

  - In h264decoder.cpp, line 59, add "AV_" to "CODEC_FLAG2_FAST"
```cpp
pH264CodecCtx->flags2 |= AV_CODEC_FLAG2_FAST;
```
  - In videoencoder.cpp, line 130, add "AV_" to "CODEC_FLAG_GLOBAL_HEADER"
```cpp
pCodecCtx->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
```
  - In videoencoder.cpp, line 783, add "AV_" to "CODEC_FLAG_GLOBAL_HEADER"
```cpp
c->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
```

I did not need to remove /usr/include from INCLUDEPATH.

**Comment by truonggiang0710** [comment]
Thanks all.
