### ISSUE TITLE
display firmware version on See3CAM_CU30 not working

### ISSUE THREAD

**Issue by arpu** [econsysqtcam/qtcam#9]
i always get 0.0.0.0 as versions string

**Comment by econsysqtcam** [comment]
Hello Arpu,

We have been trying to reproduce this issue but couldn't. Please could you let us know the following details so we could look into it for you:

1. Your Ubuntu OS version
2. How do you launch the application? Is it from Dash home or using command "sudo qtcam" from terminal?
3. When do you get this issue?
4. Are you executing some other camera application at the same time?
5. Are you executing multiple QtCAM applications at the same time?

The above would help us suggest and support better.

Thank You!

**Comment by arputcu** [comment]
Hello,

thx for all your informations
the problem was i do not start Qtcam as sudo!

starting as sudo ./Qtcam  firmware version display works fine

**Comment by arpu** [comment]
starting QtCam as sudo
firmware display works fine! 

the problem for me was i do not know, to start Qtcam  with sudo 

firmware display as normal user does not work

**Comment by arpu** [comment]
why does this needs root ? bad
